# Part 5 Task   

**RQ: Are there distinct patterns in interest about kdramas?**

Plan:   
1. Get a **list** of cleaned title names of each kdrama
2. Access daily pageviews for each kdrama and store into csv for each 
3. Graph 1: calculate total pageviews (sum across "count" column)
4. Graph 2: identify the maximum in "count" and in an additional column of "centered-date", label it as 0 and negative integers before/positive integers after.

**Table of Contents**  
1. [Exploring the kdramas_2023.csv](#sec1)
2. [Indexing and Selection](#sec3)
3. [Resampling and Frequency Conversion](#sec4)
4. [Wikipedia Revision Timeseries](#sec5)

<a id="sec1"></a>
## 1. Exploring the kdramas_2023.csv

In [1]:
import pandas as pd

In [3]:
df = pd.read_csv('kdramas_2023.csv')
df.shape

(213, 18)

In [4]:
df.columns

Index(['Unnamed: 0', 'Year', 'Title_English', 'Episodes', 'Popularity',
       'Aired', 'Aired On', 'Duration', 'Genres', 'Tags', 'Summary',
       'Title_Korean', 'Also Known As', 'Content Rating', 'Score_Votes',
       'Score', 'Ranked', 'Watchers'],
      dtype='object')

In [5]:
df.head()

,Unnamed: 0,Year,Title_English,Episodes,Popularity,Aired,Aired On,Duration,Genres,Tags,Summary,Title_Korean,Also Known As,Content Rating,Score_Votes,Score,Ranked,Watchers
0,0,2023,High Cookie (2023),20,1638,"Oct 23, 2023 - Nov 23, 2023",NaN,34 min.,"['Thriller', 'Mystery', 'Youth', 'Fantasy']","['Bully Supporting Character', 'Student Suppor...",A teen fantasy thriller drama that tells the s...,하이쿠키,"Hai Kuki , Haikuki , Hi Cookie , Привет, печен...",18+ Restricted (violence & profanity),2440,7.3,8082,15709
1,1,2023,Strangers Again (2023),12,1515,"Jan 18, 2023 - Feb 23, 2023","Wednesday, Thursday",1 hr. 10 min.,"['Law', 'Romance', 'Drama']","[""Bickering Mains' Relationship"", 'Ex-spouse R...","Divorce lawyer Oh Ha Ra, known as the “goddess...",남이 될 수 있을까?,"Can I Be Someone Else , Can I Be Someone Else?...",15+ - Teens 15 or older,5187,7.2,9766,17025
2,2,2023,Hello! This Is Starbucks (2023),19,99999,"Jun 20, 2023 - Jul 27, 2023","Tuesday, Wednesday, Thursday",1 min.,['Life'],"['Café Setting', 'Short Length Series', 'Web S...",This web drama deals with a theme based on the...,안녕하세요! 스타벅스입니다,Annyeonghaseyo! Seutabeokseuibnida,Not Yet Rated,5,5.9,99999,105
3,3,2023,Adult Kids (2023),8,9473,"Jun 19, 2023 - Aug 7, 2023",Monday,10 min.,"['Life', 'Drama']","['Female Centered Plot', 'Short Length Series'...",A hyper-realistic drama depicting the daily li...,어른애들,"Crianças Adultas , Eoreunaedeul , The Adult Li...",Not Yet Rated,181,7.1,10086,1250
4,4,2023,My Demon (2023),16,40,"Nov 24, 2023 - Jan 20, 2024","Friday, Saturday",1 hr. 6 min.,"['Action', 'Comedy', 'Romance', 'Fantasy']","['Demon Male Lead', 'Supernatural', 'Heiress F...",Do Do Hee is the successor of the Future Group...,마이데몬,"Demonul Șarmant , Maidemon , Meu Demônio Favor...",15+ - Teens 15 or older,97628,8.3,1177,165957

In [9]:
df[df['Title_English']=='My Demon (2023)']

,Unnamed: 0,Year,Title_English,Episodes,Popularity,Aired,Aired On,Duration,Genres,Tags,Summary,Title_Korean,Also Known As,Content Rating,Score_Votes,Score,Ranked,Watchers
4,4,2023,My Demon (2023),16,40,"Nov 24, 2023 - Jan 20, 2024","Friday, Saturday",1 hr. 6 min.,"['Action', 'Comedy', 'Romance', 'Fantasy']","['Demon Male Lead', 'Supernatural', 'Heiress F...",Do Do Hee is the successor of the Future Group...,마이데몬,"Demonul Șarmant , Maidemon , Meu Demônio Favor...",15+ - Teens 15 or older,97628,8.3,1177,165957

In [15]:
kdramas = df['Title_English'].tolist() 
print(len(kdramas))
kdramas[:5]

213

['High Cookie (2023)',
 'Strangers Again (2023)',
 'Hello! This Is Starbucks (2023)',
 'Adult Kids (2023)',
 'My Demon (2023)']

## 2. Wiki

In [16]:
from mwclient import Site
site = Site('en.wikipedia.org')
page = site.pages[kdramas[0]]
page

In [ ]:
from mwviews.api import PageviewsClient

p = PageviewsClient(user_agent="Kdrama Lover (wendy_wellesley@gmail.com)")
data = p.article_views('en.wikipedia', kdramas, 
                       start='20260801', end='20260831')

list(data.items())[:5]